language: python
python:
  - "3.5"
  - "3.6"
env:
  - PATH=$HOME/.cargo/bin:$PATH
before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
install:
  - pip install -e .
script:
  - python ./tests/test_py_to_rs.py
  - python ./tests/test_rs_to_py.py
  - cd ./src/rslib/ && cargo test
