[package]
name = "rustypy"
version = "0.1.2"
authors = ["IDG <iduartgomez@gmail.com>"]

[dependencies]
cpython = { git="https://github.com/dgrunwald/rust-cpython.git", features=["python-3-5"]}
libc = "*"
syntex_syntax = "*"
syntex_errors = "*"

[lib]
name = "rustypy"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
